/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3aJjZIKH5N0U= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3aJjZIKH5N0U= >>
// ----------- >>
public class Class1 {
    // ----------- << attribute.annotations@AAAAAAF3aJjaAqJfsEo= >>
    // ----------- >>
    private Movimiento ;

    public Movimiento get() {
        return ;
    }

    public void set(Movimiento ) {
        this. = ;
    }

    public void link(Movimiento _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF3aJjZIKH5N0U= >>
// ----------- >>
}