/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3OhAQZt0UGgY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3OhAQZt0UGgY= >>
// ----------- >>
public class Cliente {
    // ----------- << attribute.annotations@AAAAAAF3OhBLnN0+M1s= >>
    // ----------- >>
    private String idCliente;

    // ----------- << attribute.annotations@AAAAAAF3OhDNPt1GihE= >>
    // ----------- >>
    private String nombre;

    // ----------- << attribute.annotations@AAAAAAF3OhFILd1Phrk= >>
    // ----------- >>
    private String direccion;

    // ----------- << attribute.annotations@AAAAAAF3OhGYbd1WALE= >>
    // ----------- >>
    private String rfc;

    // ----------- << attribute.annotations@AAAAAAF3OhG/Jt1dVDc= >>
    // ----------- >>
    private String correo;

    // ----------- << attribute.annotations@AAAAAAF3OhIoy91kjRs= >>
    // ----------- >>
    private String numero;

    // ----------- << attribute.annotations@AAAAAAF3Ojd5A6pCGW4= >>
    // ----------- >>
    private Set<Cuenta>  = new HashSet<>();

    public String getIdCliente() {
        return idCliente;
    }

    public String getNombre() {
        return nombre;
    }

    public String getDireccion() {
        return direccion;
    }

    public String getRfc() {
        return rfc;
    }

    public String getCorreo() {
        return correo;
    }

    public String getNumero() {
        return numero;
    }

    public Set<Cuenta> get() {
        return ;
    }

    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public void setRfc(String rfc) {
        this.rfc = rfc;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public void link(Cuenta _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void unlink(Cuenta _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Cuenta _, Iterator<Cuenta> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF3OhAQZt0UGgY= >>
// ----------- >>
}