/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3OhRQQd6w4/Q= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3OhRQQd6w4/Q= >>
// ----------- >>
public class Cuenta {
    // ----------- << attribute.annotations@AAAAAAF3OhTIe97bAQ0= >>
    // ----------- >>
    private String numeroDeCuenta;

    // ----------- << attribute.annotations@AAAAAAF3OhUs397iuF8= >>
    // ----------- >>
    private float saldo;

    // ----------- << attribute.annotations@AAAAAAF3OhVpJt7pgzE= >>
    // ----------- >>
    private String clabe;

    // ----------- << attribute.annotations@AAAAAAF3OhW2z97xHQU= >>
    // ----------- >>
    private String tipo;

    // ----------- << attribute.annotations@AAAAAAF3OjcgtKiSfSs= >>
    // ----------- >>
    private Set<Movimiento>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF3OjdQR6l8Ri0= >>
    // ----------- >>
    private Cuenta ;

    // ----------- << attribute.annotations@AAAAAAF3OjdQR6l7LrI= >>
    // ----------- >>
    private Cuenta ;

    // ----------- << attribute.annotations@AAAAAAF3Ojd5A6pDyyQ= >>
    // ----------- >>
    private Cliente ;

    // ----------- << attribute.annotations@AAAAAAF3Ojbb56gBYD4= >>
    // ----------- >>
    private Sucursal ;

    public String getNumeroDeCuenta() {
        return numeroDeCuenta;
    }

    public float getSaldo() {
        return saldo;
    }

    public String getClabe() {
        return clabe;
    }

    public String getTipo() {
        return tipo;
    }

    public Set<Movimiento> get() {
        return ;
    }

    public Cuenta get() {
        return ;
    }

    public Cuenta get() {
        return ;
    }

    public Cliente get() {
        return ;
    }

    public Sucursal get() {
        return ;
    }

    public void setNumeroDeCuenta(String numeroDeCuenta) {
        this.numeroDeCuenta = numeroDeCuenta;
    }

    public void setSaldo(float saldo) {
        this.saldo = saldo;
    }

    public void setClabe(String clabe) {
        this.clabe = clabe;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public void set(Cuenta ) {
        this. = ;
    }

    public void set(Cuenta ) {
        this. = ;
    }

    public void set(Cliente ) {
        this. = ;
    }

    public void set(Sucursal ) {
        this. = ;
    }

    public void link(Movimiento _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void link(Cuenta _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cuenta _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cliente _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void link(Sucursal _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void unlink(Movimiento _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Movimiento _, Iterator<Movimiento> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF3OhRQQd6w4/Q= >>
// ----------- >>
}