/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3OhsjpN+D7TA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3OhsjpN+D7TA= >>
// ----------- >>
public class Empleado {
    // ----------- << attribute.annotations@AAAAAAF3OhultN+v+ls= >>
    // ----------- >>
    private String idEmpleado;

    // ----------- << attribute.annotations@AAAAAAF3OhvQXt+2vvo= >>
    // ----------- >>
    private String rfc;

    // ----------- << attribute.annotations@AAAAAAF3Ohvm5t+9fX4= >>
    // ----------- >>
    private String nombre;

    // ----------- << attribute.annotations@AAAAAAF3Ohv0Kd/EAeg= >>
    // ----------- >>
    private String puesto;

    // ----------- << attribute.annotations@AAAAAAF3aJI9H6AQvMk= >>
    // ----------- >>
    private String domicilio;

    // ----------- << attribute.annotations@AAAAAAF3OjSWYaV0vcQ= >>
    // ----------- >>
    private Sucursal ;

    private String getIdEmpleado() {
        return idEmpleado;
    }

    private String getRfc() {
        return rfc;
    }

    public String getNombre() {
        return nombre;
    }

    public String getPuesto() {
        return puesto;
    }

    public String getDomicilio() {
        return domicilio;
    }

    public Sucursal get() {
        return ;
    }

    private void setIdEmpleado(String idEmpleado) {
        this.idEmpleado = idEmpleado;
    }

    private void setRfc(String rfc) {
        this.rfc = rfc;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }

    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

    public void set(Sucursal ) {
        this. = ;
    }

    public void link(Sucursal _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF3OhsjpN+D7TA= >>
// ----------- >>
}