/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3OhYzXt76LRE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3OhYzXt76LRE= >>
// ----------- >>
public class Movimiento {
    // ----------- << attribute.annotations@AAAAAAF3OhZhvN8kHto= >>
    // ----------- >>
    private String idMovimiento;

    // ----------- << attribute.annotations@AAAAAAF3Ohae1t8r0RU= >>
    // ----------- >>
    private String tipo;

    // ----------- << attribute.annotations@AAAAAAF3Oha+ht8yDFk= >>
    // ----------- >>
    private String fecha;

    // ----------- << attribute.annotations@AAAAAAF3Ohe52985CQI= >>
    // ----------- >>
    private float monto;

    // ----------- << attribute.annotations@AAAAAAF3OjcgtKiRTfg= >>
    // ----------- >>
    private Cuenta ;

    // ----------- << attribute.annotations@AAAAAAF3aJjaAqJgRd8= >>
    // ----------- >>
    private Class1 ;

    public String getIdMovimiento() {
        return idMovimiento;
    }

    public String getTipo() {
        return tipo;
    }

    public String getFecha() {
        return fecha;
    }

    public float getMonto() {
        return monto;
    }

    public Cuenta get() {
        return ;
    }

    public Class1 get() {
        return ;
    }

    public void setIdMovimiento(String idMovimiento) {
        this.idMovimiento = idMovimiento;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public void setMonto(float monto) {
        this.monto = monto;
    }

    public void set(Cuenta ) {
        this. = ;
    }

    public void set(Class1 ) {
        this. = ;
    }

    public void link(Cuenta _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void link(Class1 _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF3OhYzXt76LRE= >>
// ----------- >>
}