/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF3OhhTr99CBhI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF3OhhTr99CBhI= >>
// ----------- >>
public class Sucursal {
    // ----------- << attribute.annotations@AAAAAAF3OhiMut9sC48= >>
    // ----------- >>
    private String numSucursal;

    // ----------- << attribute.annotations@AAAAAAF3Ohj3Xd9zrCA= >>
    // ----------- >>
    private String direccion;

    // ----------- << attribute.annotations@AAAAAAF3OhkbPN96PXA= >>
    // ----------- >>
    private String tipo;

    // ----------- << attribute.annotations@AAAAAAF3OjSWYaV1hK0= >>
    // ----------- >>
    private Set<Empleado>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF3Ojap3qdxZJY= >>
    // ----------- >>
    private Sucursal ;

    // ----------- << attribute.annotations@AAAAAAF3Ojap3qdwy58= >>
    // ----------- >>
    private Sucursal ;

    // ----------- << attribute.annotations@AAAAAAF3Ojbb56gCayo= >>
    // ----------- >>
    private Set<Cuenta>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF3aJkmfKN9QU8= >>
    // ----------- >>
    private Sucursal ;

    // ----------- << attribute.annotations@AAAAAAF3aJkmfKN88uU= >>
    // ----------- >>
    private Sucursal ;

    public String getNumSucursal() {
        return numSucursal;
    }

    public String getDireccion() {
        return direccion;
    }

    public String getTipo() {
        return tipo;
    }

    public Set<Empleado> get() {
        return ;
    }

    public Sucursal get() {
        return ;
    }

    public Sucursal get() {
        return ;
    }

    public Set<Cuenta> get() {
        return ;
    }

    public Sucursal get() {
        return ;
    }

    public Sucursal get() {
        return ;
    }

    public void setNumSucursal(String numSucursal) {
        this.numSucursal = numSucursal;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public void set(Sucursal ) {
        this. = ;
    }

    public void set(Sucursal ) {
        this. = ;
    }

    public void set(Sucursal ) {
        this. = ;
    }

    public void set(Sucursal ) {
        this. = ;
    }

    public void link(Empleado _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void link(Sucursal _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Sucursal _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cuenta _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void link(Sucursal _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Sucursal _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink(Empleado _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Empleado _, Iterator<Empleado> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink(Cuenta _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Cuenta _, Iterator<Cuenta> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF3OhhTr99CBhI= >>
// ----------- >>
}